spring:
  application:
    name: librarymanage
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/librarysystem?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 1234
server:
  port: 8080
  address: 0.0.0.0