spring:
  application:
    name: librarymanage
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/librarysystem?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 1234

  mybatis-plus:
    mapper-locations: classpath:/mapper/**/*.xml
    type-aliases-package: cn.yam.domain
    global-config:
      db-config:
        id-type: auto
        logic-delete-field: delete
        logic-not-delete-value: 0
        logic-delete-value: 1

server:
  port: 8080

logging:
  level:
    cn.yam.mapper: debug

debug: true