spring:
  datasource:
    url: jdbc:mysql://111.229.38.229:3306/lib?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: lib
    password: DdPr8aDpNtDwD5EY
  session:
    timeout: 86400
server:
  address: 0.0.0.0
